### PR TITLE
feat: make variables as default

### PR DESCRIPTION
**Pull request by gh-msvefors**
move variables from vars to default dir so that they can be overridden by the playbook using them.
fix the use of user where group is expected and vice verse.

### CODE REVIEW

**Comment by guidograzioli** [comment]
Hello Mats, thanks for contributing. Would you mind splitting the PR in two, so we can merge the fix immediately; for the vars-> defaults change, I'd like to ask some refinement

**Comment by rpelisse** [comment]
@gh-msvefors Did you see @guidograzioli comment above?

**Comment by guidograzioli** [comment]
Fix #38

**Comment by guidograzioli** [comment]
My additional commit on top of @gh-msvefors work adds a dict in vars/main.yml which is used internally, created from the defaults, which were given a value too; the module_directory variable is only once necessary now since it contains the jboss home in the path

**Review by rpelisse — APPROVED** [review]
@guidograzioli LGTM

**Pull request merged**
