### PR TITLE
Update the WildFly version to 27.0.0.Final

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
1) Updated the WildFly version to 27.0.0.Final
2) The newest WildFly version required JDK 11 or a newer version. Updated that accordingly.

### CODE REVIEW

**Review by rpelisse — APPROVED** [review]
@guidograzioli LGTM... Any comments on your side?

**Comment by rpelisse** [comment]
@RanabirChakraborty can you rebase your PR? Thanks!

**Comment by RanabirChakraborty** [comment]
@rpelisse Done, Thanks!

**Comment by rpelisse** [comment]
@RanabirChakraborty a few more lint issues :)

```
ERROR: roles/wildfly_driver/defaults/main.yml:5:1: error: syntax error: could not find expected ':' (syntax)
ERROR: roles/wildfly_driver/defaults/main.yml:5:1: unparsable-with-libyaml: while scanning a simple key - could not find expected ':'
```

**Pull request merged**
