### PR TITLE
Correct typo in task name

### PR DESCRIPTION
**Pull request by aushacker**

### CODE REVIEW

**Comment by aushacker** [comment]
Superceeds #25

**Comment by aushacker** [comment]
Fixes #16

**Comment by rpelisse** [comment]
Superseeds [PR25](https://github.com/ansible-middleware/wildfly/pull/26)

**Review by rpelisse — APPROVED** [review]
LGTM! @guidograzioli Anymore comments on your side?

**Review by guidograzioli — APPROVED** [review]
LGTM

**Comment by aushacker** [comment]
@rpelisse could you please merge branch ansible-middleware:ensure-dir into main? Thanks!

**Pull request merged**
