### PR TITLE
Update EAP version to integrate EAP 8.0.0.Beta version.

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Update EAP version to integrate EAP 8.0.0.Beta version.

### CODE REVIEW

**Comment by RanabirChakraborty** [comment]
@guidograzioli Can you please review this PR.

**Comment by guidograzioli** [comment]
Can you rebase on main pls?

**Review by guidograzioli — APPROVED** [review]
LGTM! @rpelisse if you wanna take a look too

**Review by rpelisse — APPROVED** [review]

**Comment by rpelisse** [comment]
@guidograzioli LGTM merge at your convenience!

**Pull request merged**
