### PR TITLE
Ensure dir

### PR DESCRIPTION
**Pull request by rpelisse**
Superseed [PR19](https://github.com/ansible-middleware/wildfly/pull/19.

@aushacker Can you confirm this looks OK to you?
@guidograzioli any last comment on this?

### CODE REVIEW

**Comment by rpelisse** [comment]
@aushacker CI fails, it seems there is some error spot by lint. Can you take a look? Thanks!

**Comment by guidograzioli** [comment]
(the ansible-lint output is quite difficult to read because even if errors are lowered to warning, they still show in red as errors) This two are actually failing:
```
  roles/wildfly_install/tasks/main.yml:14: task_has_valid_name Invalid task name 'Ensures archive_dir {{ wildfly_install.archive_dir }} exists.'
  roles/wildfly_systemd/tasks/main.yml:11: unnamed-task All tasks should be named
```
The first wants "Ensure" instead of "Ensures", the second wants a `name: ` on the task

**Comment by aushacker** [comment]
Thanks @guidograzioli, I had picked up on that. This is the first time I've worked with multiple Github repos and I'm having trouble getting the branching / push right.

**Comment by rpelisse** [comment]
@aushacker no worries! Git is awesome, but it can get complicated. I'm still trying to understand what the purpose of the _git rerere_ command ;) !

Can you fixed what Guido pointed out and set up a new PR?

**Comment by aushacker** [comment]
@rpelisse done

**Comment by rpelisse** [comment]
Superseeded by [PR26](https://github.com/ansible-middleware/wildfly/pull/26)

**Comment by rpelisse** [comment]
@aushacker Sorry, I thought your new PR would have superseeded this one. I've reopened it and I will merge unless CI fails.

**Pull request merged**
