### PR TITLE
Down assets

### PR DESCRIPTION
**Pull request by rpelisse**
DONOTMERGE

### CODE REVIEW

**Comment by rpelisse** [comment]
@guidograzioli this might go away when 'defautls' is ready, but in the meantime, do you have any issue with merging this?

**Comment by guidograzioli** [comment]
> @guidograzioli this might go away when 'defautls' is ready, but in the meantime, do you have any issue with merging this?

good to me, we just have to remember the linter setting

**Comment by rpelisse** [comment]
Oh no, I did not meant to disable lint. Let me fix that.

**Comment by rpelisse** [comment]
@guidograzioli OK, lint reactivated, assuming the gh action test passes, I'll merge this.

**Pull request merged**
